### bu yangi client yaratish uchun ishlatiladi
POST http://localhost:8084/client/create
Content-Type: application/json

{
  "name": "wertyu",
  "surname": "ertyu",
  "middleName": "ertyui o'g'li",
  "phone": "+998991970000",
  "profileName": "Bank"
}

<> 2022-05-25T191554.200.json

### bu yaratilgan clientni tel raqami bilan topib uni malumotlarini yangilaydi
PUT http://localhost:8084/client/update/+998953011213
Content-Type: application/json

{
  "name": "Soyibjon",
  "surname": "Islomov",
  "middleName": "Davlatbek o'g'li",
  "profileName": "Click"
}

<> 2022-05-25T191726.200.json

### bu clientni statusini active qilish uchun ishlatiladi birinchi yaratilganda NO_ACTIVE bo'ladi
PUT http://localhost:8084/client/updateStatus/+998991970000
Content-Type: application/json

<> 2022-05-25T191933.200.json

### bu narsa telefon raqamin yangilash uchun ishlatiladi
PUT http://localhost:8084/client/updatePhone/+998991970000
Content-Type: application/json

{
  "phone": "+998335222222"
}

<> 2022-05-25T192433.200.json

### bu barcah clientni yaratilgan vaqti bilan pagination qilib beradi limit 5 ta
GET http://localhost:8084/client/pagination
Content-Type: application/json

<> 2022-05-25T192412.200.json

### bu tel raqamga kimga tegishli ekanligini ko'rib beradi
GET http://localhost:8084/client/getById/+998335222222/Bank
Content-Type: application/json

<> 2022-05-26T145023.200.json
<> 2022-05-26T144906.400.json

### bu clientlarni profileName si bo'yicha hammasini olib beradi
GET http://localhost:8084/client/AllClient_viz_profileName/Bank
Content-Type: application/json

<> 2022-05-25T193015.200.json